-- Expand the global catalogue without changing existing IDs. Existing swipes
-- and matches therefore remain attached to the same names.
--
-- The previous two catalogue additions intentionally prioritised getting real
-- spellings into production, but left some cards without origin/meaning. Fill
-- those blanks first so every global catalogue card has useful metadata.
update public.names as n
set
  origin = coalesce(n.origin, metadata.origin),
  meaning = coalesce(n.meaning, metadata.meaning)
from (values
  ('Elijah', 'boy', 'Hebrew', 'The Lord is my God'),
  ('William', 'boy', 'Germanic', 'Resolute protector'),
  ('Henry', 'boy', 'Germanic', 'Home ruler'),
  ('Theodore', 'boy', 'Greek', 'Gift of God'),
  ('Michael', 'boy', 'Hebrew', 'Who is like God'),
  ('Alexander', 'boy', 'Greek', 'Defender of people'),
  ('Ethan', 'boy', 'Hebrew', 'Enduring, strong'),
  ('Owen', 'boy', 'Welsh', 'Young warrior'),
  ('John', 'boy', 'Hebrew', 'God is gracious'),
  ('Asher', 'boy', 'Hebrew', 'Happy, blessed'),
  ('Joseph', 'boy', 'Hebrew', 'God will add'),
  ('Jacob', 'boy', 'Hebrew', 'He who supplants'),
  ('Logan', 'boy', 'Scottish Gaelic', 'Little hollow'),
  ('Luke', 'boy', 'Greek', 'From Lucania'),
  ('Matthew', 'boy', 'Hebrew', 'Gift of God'),
  ('Dylan', 'boy', 'Welsh', 'Son of the sea'),
  ('Anthony', 'boy', 'Latin', 'Priceless one'),
  ('Miles', 'boy', 'Latin', 'Soldier'),
  ('Charles', 'boy', 'Germanic', 'Free man'),
  ('Caleb', 'boy', 'Hebrew', 'Faithful, wholehearted'),
  ('Christopher', 'boy', 'Greek', 'Bearer of Christ'),
  ('Joshua', 'boy', 'Hebrew', 'The Lord is salvation'),
  ('Andrew', 'boy', 'Greek', 'Brave, strong'),
  ('Roman', 'boy', 'Latin', 'Citizen of Rome'),
  ('Cameron', 'boy', 'Scottish Gaelic', 'Scottish clan name'),
  ('Wesley', 'boy', 'English', 'Western meadow'),
  ('Axel', 'boy', 'Hebrew', 'Father of peace'),
  ('Christian', 'boy', 'Latin', 'Follower of Christ'),
  ('Eli', 'boy', 'Hebrew', 'My God'),
  ('Ryan', 'boy', 'Irish', 'Little king'),
  ('Jonathan', 'boy', 'Hebrew', 'God has given'),
  ('Beau', 'boy', 'French', 'Handsome'),
  ('Silas', 'boy', 'Latin', 'Man of the forest'),
  ('Leonardo', 'boy', 'Germanic', 'Brave lion'),
  ('Robert', 'boy', 'Germanic', 'Bright fame'),
  ('Thiago', 'boy', 'Portuguese', 'He who supplants'),
  ('Gael', 'boy', 'Breton', 'A Gaelic person'),
  ('Dominic', 'boy', 'Latin', 'Of the Lord'),
  ('Xavier', 'boy', 'Basque', 'New house'),
  ('Vincent', 'boy', 'Latin', 'Conquering'),
  ('Jasper', 'boy', 'Persian', 'Treasurer'),
  ('Emiliano', 'boy', 'Latin', 'Eager, striving'),
  ('Luis', 'boy', 'Germanic', 'Famous warrior'),
  ('Carlos', 'boy', 'Germanic', 'Free man'),
  ('Juan', 'boy', 'Hebrew', 'God is gracious'),
  ('Jude', 'boy', 'Hebrew', 'Praised'),
  ('Matteo', 'boy', 'Hebrew', 'Gift of God'),
  ('Leon', 'boy', 'Greek', 'Lion'),
  ('Arlo', 'boy', 'English', 'Fortified hill'),
  ('Antonio', 'boy', 'Latin', 'Priceless one'),
  ('Miguel', 'boy', 'Hebrew', 'Who is like God'),
  ('Alejandro', 'boy', 'Greek', 'Defender of people'),
  ('Sophia', 'girl', 'Greek', 'Wisdom'),
  ('Ava', 'girl', 'Germanic', 'Life, voice'),
  ('Evelyn', 'girl', 'English', 'Desired child'),
  ('Eleanor', 'girl', 'Old French', 'Shining light'),
  ('Elizabeth', 'girl', 'Hebrew', 'God is my oath'),
  ('Gianna', 'girl', 'Hebrew', 'God is gracious'),
  ('Scarlett', 'girl', 'English', 'Scarlet red'),
  ('Violet', 'girl', 'Latin', 'Violet flower'),
  ('Chloe', 'girl', 'Greek', 'Young green shoot'),
  ('Abigail', 'girl', 'Hebrew', 'Joy of the father'),
  ('Aria', 'girl', 'Italian', 'Air, melody'),
  ('Penelope', 'girl', 'Greek', 'Weaver'),
  ('Ellie', 'girl', 'English', 'Shining light'),
  ('Layla', 'girl', 'Arabic', 'Night'),
  ('Eliana', 'girl', 'Hebrew', 'My God has answered'),
  ('Grace', 'girl', 'Latin', 'Grace, favour'),
  ('Lucy', 'girl', 'Latin', 'Light'),
  ('Willow', 'girl', 'English', 'Willow tree'),
  ('Victoria', 'girl', 'Latin', 'Victory'),
  ('Stella', 'girl', 'Latin', 'Star'),
  ('Leah', 'girl', 'Hebrew', 'Weary, delicate'),
  ('Lillian', 'girl', 'Latin', 'Lily'),
  ('Delilah', 'girl', 'Hebrew', 'Delicate'),
  ('Natalie', 'girl', 'Latin', 'Born at Christmas'),
  ('Sadie', 'girl', 'Hebrew', 'Princess'),
  ('Ruby', 'girl', 'Latin', 'Red gemstone'),
  ('Josephine', 'girl', 'Hebrew', 'God will add'),
  ('Claire', 'girl', 'Latin', 'Bright, clear'),
  ('Alice', 'girl', 'Germanic', 'Noble'),
  ('Audrey', 'girl', 'Old English', 'Noble strength'),
  ('Adeline', 'girl', 'Germanic', 'Noble'),
  ('Aaliyah', 'girl', 'Arabic', 'Exalted'),
  ('Eloise', 'girl', 'Germanic', 'Renowned in battle'),
  ('Caroline', 'girl', 'Germanic', 'Free woman'),
  ('Vivian', 'girl', 'Latin', 'Alive'),
  ('Bella', 'girl', 'Italian', 'Beautiful'),
  ('Gabriella', 'girl', 'Hebrew', 'God is my strength'),
  ('Cora', 'girl', 'Greek', 'Maiden'),
  ('Maria', 'girl', 'Hebrew', 'Beloved'),
  ('Liliana', 'girl', 'Latin', 'Lily'),
  ('Lydia', 'girl', 'Greek', 'Woman from Lydia'),
  ('Athena', 'girl', 'Greek', 'Goddess of wisdom'),
  ('Ayla', 'girl', 'Turkish', 'Halo of moonlight'),
  ('Daisy', 'girl', 'English', 'Daisy flower'),
  ('Rose', 'girl', 'Latin', 'Rose flower'),
  ('Sienna', 'girl', 'Italian', 'Reddish earth'),
  ('Esther', 'girl', 'Persian', 'Star'),
  ('Catalina', 'girl', 'Greek', 'Pure'),
  ('Juliette', 'girl', 'Latin', 'Youthful'),
  ('Amaya', 'girl', 'Basque', 'Basque place name'),
  ('June', 'girl', 'Latin', 'Young'),
  ('Amira', 'girl', 'Arabic', 'Princess'),
  ('Rosalie', 'girl', 'Latin', 'Rose'),
  ('Gemma', 'girl', 'Latin', 'Gem'),
  ('Alexandra', 'girl', 'Greek', 'Defender of people'),
  ('Phoebe', 'girl', 'Greek', 'Bright, radiant'),
  ('Milou', 'girl', 'French', 'Gentle strength'),
  ('Lieke', 'girl', 'Dutch', 'Angel-like'),
  ('Musa', 'boy', 'Arabic', 'Drawn from the water'),
  ('Oos', 'boy', 'Frisian', 'Short form of names beginning with Os'),
  ('Lucía', 'girl', 'Latin', 'Light'),
  ('Martín', 'boy', 'Latin', 'Of Mars'),
  ('Martina', 'girl', 'Latin', 'Of Mars'),
  ('Manuel', 'boy', 'Hebrew', 'God is with us'),
  ('Marc', 'boy', 'Latin', 'Of Mars'),
  ('Laia', 'girl', 'Greek', 'Well-spoken'),
  ('Ravi', 'boy', 'Sanskrit', 'Sun'),
  ('Maitê', 'girl', 'Basque', 'Beloved'),
  ('Heitor', 'boy', 'Greek', 'Holding fast'),
  ('Bernardo', 'boy', 'Germanic', 'Brave as a bear'),
  ('Davi', 'boy', 'Hebrew', 'Beloved'),
  ('Benício', 'boy', 'Latin', 'Blessed'),
  ('Pedro', 'boy', 'Greek', 'Rock'),
  ('Antonella', 'girl', 'Latin', 'Priceless one'),
  ('Ísis', 'girl', 'Egyptian', 'Throne'),
  ('Heloísa', 'girl', 'Germanic', 'Healthy, wide'),
  ('Joaquim', 'boy', 'Hebrew', 'God establishes'),
  ('Henrique', 'boy', 'Germanic', 'Home ruler'),
  ('Mavie', 'girl', 'French', 'My life'),
  ('Melissa', 'girl', 'Greek', 'Honeybee')
) as metadata(value, gender, origin, meaning)
where n.couple_id is null
  and lower(n.value) = lower(metadata.value)
  and n.gender = metadata.gender::public.name_gender;

-- Spain: INE, 100 most frequent newborn names for 2024.
-- https://www.ine.es/daco/daco42/nombyapel/nomnac24.xlsx
insert into public.names (value, gender, origin, meaning, popularity, works_in) values
  ('Álvaro', 'boy', 'Germanic', 'Guardian of all', 10, '{es,pt}'),
  ('Gonzalo', 'boy', 'Germanic', 'Ready for battle', 14, '{es}'),
  ('Nicolás', 'boy', 'Greek', 'Victory of the people', 22, '{es}'),
  ('Marcos', 'boy', 'Latin', 'Of Mars', 24, '{es,pt}'),
  ('Javier', 'boy', 'Basque', 'New house', 31, '{es}'),
  ('Izan', 'boy', 'Spanish', 'Enduring, strong', 32, '{es}'),
  ('Rodrigo', 'boy', 'Germanic', 'Famous ruler', 33, '{es,pt}'),
  ('José', 'boy', 'Hebrew', 'God will add', 35, '{es,pt}'),
  ('Ángel', 'boy', 'Greek', 'Messenger', 36, '{es}'),
  ('Jaime', 'boy', 'Hebrew', 'He who supplants', 42, '{es}'),
  ('Pau', 'boy', 'Catalan', 'Small, humble', 46, '{es}'),
  ('Guillermo', 'boy', 'Germanic', 'Resolute protector', 47, '{es}'),
  ('Jorge', 'boy', 'Greek', 'Farmer', 48, '{es,pt}'),
  ('Héctor', 'boy', 'Greek', 'Holding fast', 49, '{es}'),
  ('Eric', 'boy', 'Norse', 'Eternal ruler', 50, '{en,es,nl,fr}'),
  ('Francisco', 'boy', 'Latin', 'Free one', 52, '{es,pt}'),
  ('Iker', 'boy', 'Basque', 'Visitation', 54, '{es}'),
  ('Jesús', 'boy', 'Hebrew', 'The Lord saves', 55, '{es}'),
  ('Sergio', 'boy', 'Latin', 'Guardian, attendant', 57, '{es,pt}'),
  ('Julen', 'boy', 'Basque', 'Youthful', 64, '{es}'),
  ('Biel', 'boy', 'Catalan', 'God is my strength', 65, '{es}'),
  ('Unai', 'boy', 'Basque', 'Shepherd', 66, '{es}'),
  ('Nil', 'boy', 'Catalan', 'The Nile', 67, '{es}'),
  ('Saúl', 'boy', 'Hebrew', 'Asked for', 68, '{es}'),
  ('Martí', 'boy', 'Catalan', 'Of Mars', 69, '{es}'),
  ('Ares', 'boy', 'Greek', 'God of war', 70, '{es}'),
  ('Erik', 'boy', 'Norse', 'Eternal ruler', 75, '{en,es,nl,fr}'),
  ('Pol', 'boy', 'Catalan', 'Small, humble', 77, '{es}'),
  ('Aleix', 'boy', 'Catalan', 'Defender, helper', 78, '{es}'),
  ('Fernando', 'boy', 'Germanic', 'Bold voyager', 79, '{es,pt}'),
  ('Rayan', 'boy', 'Arabic', 'Well-watered, lush', 80, '{en,es,nl,fr,pt}'),
  ('Jan', 'boy', 'Hebrew', 'God is gracious', 81, '{en,es,nl,fr}'),
  ('Ignacio', 'boy', 'Latin', 'Fiery', 82, '{es}'),
  ('Joel', 'boy', 'Hebrew', 'The Lord is God', 83, '{en,es,nl,fr,pt}'),
  ('Alberto', 'boy', 'Germanic', 'Noble and bright', 84, '{es,pt}'),
  ('Arnau', 'boy', 'Catalan', 'Eagle ruler', 85, '{es}'),
  ('Ander', 'boy', 'Basque', 'Brave, strong', 86, '{es}'),
  ('Ismael', 'boy', 'Hebrew', 'God will hear', 87, '{es,pt}'),
  ('Luka', 'boy', 'Latin', 'Light', 88, '{en,es,nl,fr,pt}'),
  ('Máximo', 'boy', 'Latin', 'The greatest', 97, '{es,pt}'),
  ('Vega', 'girl', 'Spanish', 'Meadow, fertile plain', 5, '{es}'),
  ('Carla', 'girl', 'Germanic', 'Free woman', 14, '{en,es,nl,fr,pt}'),
  ('Gala', 'girl', 'Latin', 'Festive, joyful', 16, '{es,fr,pt}'),
  ('Jimena', 'girl', 'Spanish', 'One who listens', 20, '{es}'),
  ('Claudia', 'girl', 'Latin', 'Roman family name', 23, '{en,es,nl,fr,pt}'),
  ('Alba', 'girl', 'Latin', 'Dawn', 25, '{en,es,nl,fr,pt}'),
  ('Candela', 'girl', 'Latin', 'Candle, light', 27, '{es}'),
  ('Manuela', 'girl', 'Hebrew', 'God is with us', 28, '{es,pt}'),
  ('Triana', 'girl', 'Spanish', 'Place name from Seville', 30, '{es}'),
  ('Alejandra', 'girl', 'Greek', 'Defender of people', 31, '{es}'),
  ('Ana', 'girl', 'Hebrew', 'Grace, favour', 33, '{en,es,nl,fr,pt}'),
  ('Aitana', 'girl', 'Spanish', 'Spanish mountain name', 35, '{es}'),
  ('Carlota', 'girl', 'Germanic', 'Free woman', 36, '{es,pt}'),
  ('Blanca', 'girl', 'Germanic', 'White, bright', 37, '{es}'),
  ('Abril', 'girl', 'Latin', 'April, opening', 42, '{es,pt}'),
  ('Rocío', 'girl', 'Spanish', 'Dew', 47, '{es}'),
  ('Marta', 'girl', 'Aramaic', 'Lady, mistress', 48, '{en,es,nl,fr,pt}'),
  ('Leire', 'girl', 'Basque', 'Basque monastery name', 55, '{es}'),
  ('Ona', 'girl', 'Catalan', 'Good', 56, '{es}'),
  ('India', 'girl', 'Greek', 'Land of the Indus', 57, '{en,es,nl,fr,pt}'),
  ('Ariadna', 'girl', 'Greek', 'Most holy', 58, '{es}'),
  ('Julieta', 'girl', 'Latin', 'Youthful', 59, '{es}'),
  ('Iria', 'girl', 'Galician', 'Ancient Galician place name', 65, '{es}'),
  ('Violeta', 'girl', 'Latin', 'Violet flower', 67, '{es,pt}'),
  ('Ángela', 'girl', 'Greek', 'Messenger', 68, '{es}'),
  ('Mar', 'girl', 'Spanish', 'Sea', 70, '{es}'),
  ('Aina', 'girl', 'Catalan', 'Grace, favour', 72, '{es}'),
  ('Nour', 'girl', 'Arabic', 'Light', 75, '{en,es,nl,fr,pt}'),
  ('Adara', 'girl', 'Hebrew', 'Noble', 78, '{en,es,nl}'),
  ('Ainara', 'girl', 'Basque', 'Swallow bird', 79, '{es}'),
  ('Andrea', 'girl', 'Greek', 'Brave, strong', 80, '{en,es,nl,fr,pt}'),
  ('Yasmin', 'girl', 'Persian', 'Jasmine flower', 81, '{en,es,nl,fr,pt}'),
  ('Ainhoa', 'girl', 'Basque', 'Basque place name', 83, '{es}'),
  ('Alana', 'girl', 'Celtic', 'Harmony, beauty', 84, '{en,es,nl,fr,pt}'),
  ('Macarena', 'girl', 'Spanish', 'Place name from Seville', 85, '{es}'),
  ('Naia', 'girl', 'Basque', 'Wave, sea foam', 86, '{en,es,nl,fr,pt}'),
  ('Jana', 'girl', 'Hebrew', 'God is gracious', 87, '{en,es,nl,fr,pt}'),
  ('Elsa', 'girl', 'Hebrew', 'God is my oath', 88, '{en,es,nl,fr,pt}'),
  ('Elia', 'girl', 'Hebrew', 'The Lord is my God', 91, '{en,es,nl,fr,pt}'),
  ('Teresa', 'girl', 'Greek', 'Summer, harvest', 99, '{en,es,nl,fr,pt}')
on conflict do nothing;

-- England and Wales: ONS top 100 baby names for 2025.
-- https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/datasets/babynamesenglandandwalesbabynamesstatisticsboys
-- https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/datasets/babynamesenglandandwalesbabynamesstatisticsgirls
insert into public.names (value, gender, origin, meaning, popularity, works_in) values
  ('Muhammad', 'boy', 'Arabic', 'Praised', 1, '{en,nl,fr}'),
  ('George', 'boy', 'Greek', 'Farmer', 7, '{en}'),
  ('Oscar', 'boy', 'Irish', 'Deer friend', 8, '{en,es,nl,fr,pt}'),
  ('Freddie', 'boy', 'Germanic', 'Peaceful ruler', 10, '{en,nl}'),
  ('Archie', 'boy', 'Germanic', 'Genuine, brave', 11, '{en}'),
  ('Alfie', 'boy', 'Old English', 'Wise counsel', 16, '{en}'),
  ('Rory', 'boy', 'Irish', 'Red king', 17, '{en,nl}'),
  ('Finley', 'boy', 'Scottish Gaelic', 'Fair warrior', 18, '{en}'),
  ('Harry', 'boy', 'Germanic', 'Home ruler', 19, '{en,nl}'),
  ('Albie', 'boy', 'Germanic', 'Noble, bright', 21, '{en}'),
  ('Louie', 'boy', 'Germanic', 'Famous warrior', 28, '{en,fr}'),
  ('Reuben', 'boy', 'Hebrew', 'Behold, a son', 29, '{en,nl}'),
  ('Edward', 'boy', 'Old English', 'Wealthy guardian', 31, '{en,nl}'),
  ('Oakley', 'boy', 'English', 'Oak clearing', 33, '{en}'),
  ('Teddy', 'boy', 'Greek', 'Gift of God', 34, '{en,nl}'),
  ('Reggie', 'boy', 'Germanic', 'Advisor to the ruler', 37, '{en}'),
  ('Ronnie', 'boy', 'Norse', 'Mighty ruler', 39, '{en,nl}'),
  ('Hudson', 'boy', 'English', 'Son of Hugh', 43, '{en}'),
  ('Tommy', 'boy', 'Aramaic', 'Twin', 44, '{en,nl}'),
  ('Sonny', 'boy', 'English', 'Son', 45, '{en,nl}'),
  ('Louis', 'boy', 'Germanic', 'Famous warrior', 49, '{en,nl,fr}'),
  ('Harrison', 'boy', 'English', 'Son of Harry', 50, '{en}'),
  ('Frederick', 'boy', 'Germanic', 'Peaceful ruler', 52, '{en}'),
  ('Albert', 'boy', 'Germanic', 'Noble and bright', 57, '{en,es,nl,fr}'),
  ('Zachary', 'boy', 'Hebrew', 'God remembers', 75, '{en}'),
  ('Florence', 'girl', 'Latin', 'Flourishing', 5, '{en,nl,fr}'),
  ('Poppy', 'girl', 'English', 'Poppy flower', 7, '{en}'),
  ('Elsie', 'girl', 'Hebrew', 'God is my oath', 8, '{en,nl}'),
  ('Mabel', 'girl', 'Latin', 'Lovable', 16, '{en,es,nl}'),
  ('Matilda', 'girl', 'Germanic', 'Mighty in battle', 19, '{en,es,nl,fr,pt}'),
  ('Arabella', 'girl', 'Latin', 'Graceful, yielding to prayer', 22, '{en,es,nl}'),
  ('Harper', 'girl', 'English', 'Harp player', 23, '{en}'),
  ('Rosie', 'girl', 'Latin', 'Rose', 24, '{en,nl}'),
  ('Hallie', 'girl', 'English', 'Dweller by the meadow', 29, '{en}'),
  ('Lottie', 'girl', 'Germanic', 'Free woman', 31, '{en,nl}'),
  ('Evie', 'girl', 'Hebrew', 'Life', 35, '{en,nl}'),
  ('Millie', 'girl', 'Germanic', 'Gentle strength', 36, '{en,nl}'),
  ('Maisie', 'girl', 'Greek', 'Pearl', 43, '{en}'),
  ('Esme', 'girl', 'French', 'Esteemed, beloved', 45, '{en,nl,fr}'),
  ('Olive', 'girl', 'Latin', 'Olive tree', 47, '{en,fr}'),
  ('Bonnie', 'girl', 'Scottish', 'Pretty, cheerful', 48, '{en}'),
  ('Elodie', 'girl', 'French', 'Foreign riches', 49, '{en,nl,fr}'),
  ('Isabelle', 'girl', 'Hebrew', 'God is my oath', 54, '{en,nl,fr}'),
  ('Ottilie', 'girl', 'Germanic', 'Prosperous in battle', 55, '{en,nl,fr}'),
  ('Harriet', 'girl', 'Germanic', 'Home ruler', 59, '{en}'),
  ('Lyla', 'girl', 'Arabic', 'Night', 61, '{en}'),
  ('Orla', 'girl', 'Irish', 'Golden princess', 64, '{en}'),
  ('Eliza', 'girl', 'Hebrew', 'God is my oath', 65, '{en,nl}'),
  ('Thea', 'girl', 'Greek', 'Goddess, divine', 66, '{en,nl}'),
  ('Imogen', 'girl', 'Celtic', 'Maiden', 69, '{en}')
on conflict do nothing;

-- France and Belgium: INSEE and Statbel 2025 newborn rankings.
-- https://www.insee.fr/fr/statistiques/8595099
-- https://statbel.fgov.be/fr/themes/population/noms-et-prenoms/prenoms-filles-et-garcons
insert into public.names (value, gender, origin, meaning, popularity, works_in) values
  ('Achille', 'boy', 'Greek', 'Hero of Greek legend', 28, '{fr}'),
  ('Mathis', 'boy', 'Hebrew', 'Gift of God', 22, '{fr}'),
  ('Gaspard', 'boy', 'Persian', 'Treasurer', 37, '{fr}'),
  ('Basile', 'boy', 'Greek', 'Royal', 39, '{fr}'),
  ('Naël', 'boy', 'Arabic', 'One who attains his goal', 49, '{fr}'),
  ('Georges', 'boy', 'Greek', 'Farmer', 41, '{fr}'),
  ('César', 'boy', 'Latin', 'Roman imperial name', 57, '{es,fr,pt}'),
  ('Noé', 'boy', 'Hebrew', 'Rest, comfort', 51, '{es,fr}'),
  ('Henri', 'boy', 'Germanic', 'Home ruler', 49, '{nl,fr}'),
  ('Imran', 'boy', 'Arabic', 'Prosperity', 48, '{en,es,nl,fr,pt}'),
  ('Lucien', 'boy', 'Latin', 'Light', 58, '{fr}'),
  ('Viktor', 'boy', 'Latin', 'Conqueror', 58, '{en,nl,fr}'),
  ('Gust', 'boy', 'Latin', 'Majestic', 74, '{nl}'),
  ('Maurice', 'boy', 'Latin', 'From Mauritania', 64, '{en,nl,fr}'),
  ('Lio', 'boy', 'Latin', 'Lion', 51, '{en,es,nl,fr,pt}'),
  ('Gaston', 'boy', 'Germanic', 'Guest, stranger', 63, '{nl,fr}'),
  ('Yanis', 'boy', 'Hebrew', 'God is gracious', 61, '{fr}'),
  ('Ibrahim', 'boy', 'Arabic', 'Father of many', 45, '{en,es,nl,fr,pt}'),
  ('Marceau', 'boy', 'Latin', 'Young warrior', 99, '{fr}'),
  ('Marius', 'boy', 'Latin', 'Of Mars', 90, '{en,nl,fr}'),
  ('Louise', 'girl', 'Germanic', 'Famous warrior', 3, '{en,nl,fr}'),
  ('Ambre', 'girl', 'French', 'Amber gemstone', 66, '{fr}'),
  ('Romy', 'girl', 'Germanic', 'Dew of the sea', 35, '{en,nl,fr}'),
  ('Adèle', 'girl', 'Germanic', 'Noble', 62, '{fr}'),
  ('Lucie', 'girl', 'Latin', 'Light', 9, '{nl,fr}'),
  ('Inaya', 'girl', 'Arabic', 'Care, concern', 21, '{en,es,nl,fr,pt}'),
  ('Giulia', 'girl', 'Latin', 'Youthful', 26, '{en,nl,fr}'),
  ('Billie', 'girl', 'Germanic', 'Resolute protector', 28, '{en,nl,fr}'),
  ('Jeanne', 'girl', 'Hebrew', 'God is gracious', 28, '{nl,fr}'),
  ('Alix', 'girl', 'Germanic', 'Noble', 30, '{fr}'),
  ('Léa', 'girl', 'Hebrew', 'Weary, delicate', 31, '{fr}'),
  ('Mona', 'girl', 'Irish', 'Noble, good', 38, '{en,es,nl,fr,pt}'),
  ('Renée', 'girl', 'Latin', 'Reborn', 37, '{en,nl,fr}'),
  ('Maryam', 'girl', 'Hebrew', 'Beloved', 72, '{en,es,nl,fr,pt}'),
  ('Amélie', 'girl', 'Germanic', 'Industrious', 52, '{nl,fr}'),
  ('Céleste', 'girl', 'Latin', 'Heavenly', 61, '{es,fr}'),
  ('Léonie', 'girl', 'Latin', 'Lioness', 55, '{nl,fr}'),
  ('Esmée', 'girl', 'French', 'Esteemed, beloved', 57, '{nl,fr}'),
  ('Clémence', 'girl', 'Latin', 'Merciful, gentle', 82, '{fr}'),
  ('Margaux', 'girl', 'Greek', 'Pearl', 90, '{nl,fr}')
on conflict do nothing;

-- Portuguese and Brazilian spellings. Portugal source: the IRN official list
-- of admitted given names. Brazil source: Registro Civil transparency portal.
-- https://irn.justica.gov.pt/Servicos/Cidadao/Nascimento/Composicao-do-nome
-- https://transparencia.registrocivil.org.br/inicio
insert into public.names (value, gender, origin, meaning, popularity, works_in) values
  ('Afonso', 'boy', 'Germanic', 'Noble and ready', null, '{pt}'),
  ('Duarte', 'boy', 'Old English', 'Wealthy guardian', null, '{pt}'),
  ('Lourenço', 'boy', 'Latin', 'From Laurentum', null, '{pt}'),
  ('Martim', 'boy', 'Latin', 'Of Mars', null, '{pt}'),
  ('Salvador', 'boy', 'Latin', 'Saviour', null, '{es,pt}'),
  ('Gonçalo', 'boy', 'Germanic', 'Ready for battle', null, '{pt}'),
  ('João', 'boy', 'Hebrew', 'God is gracious', null, '{pt}'),
  ('Vicente', 'boy', 'Latin', 'Conquering', null, '{es,pt}'),
  ('Guilherme', 'boy', 'Germanic', 'Resolute protector', null, '{pt}'),
  ('Cauã', 'boy', 'Tupi', 'Hawk', null, '{pt}'),
  ('Leonor', 'girl', 'Old French', 'Shining light', null, '{es,pt}'),
  ('Matilde', 'girl', 'Germanic', 'Mighty in battle', null, '{es,pt}'),
  ('Beatriz', 'girl', 'Latin', 'Bringer of joy', null, '{es,pt}'),
  ('Benedita', 'girl', 'Latin', 'Blessed', null, '{pt}'),
  ('Francisca', 'girl', 'Latin', 'Free one', null, '{es,pt}'),
  ('Margarida', 'girl', 'Greek', 'Pearl', null, '{pt}'),
  ('Madalena', 'girl', 'Hebrew', 'Woman from Magdala', null, '{pt}'),
  ('Luísa', 'girl', 'Germanic', 'Famous warrior', null, '{pt}'),
  ('Letícia', 'girl', 'Latin', 'Joy', null, '{pt}'),
  ('Liz', 'girl', 'Hebrew', 'God is my oath', 31, '{en,nl,pt}')
on conflict do nothing;

-- Additional current names from Norway (SSB) and Ireland (CSO), both 2025.
-- https://www.ssb.no/befolkning/navn/statistikk/navn/artikler/dette-var-de-mest-populaere-navnene-i-2025
-- https://www.cso.ie/en/releasesandpublications/ep/p-ibn/irishbabiesnames2025/
insert into public.names (value, gender, origin, meaning, popularity, works_in) values
  ('Isak', 'boy', 'Hebrew', 'He will laugh', 8, '{en,nl}'),
  ('Ludvig', 'boy', 'Germanic', 'Famous warrior', 10, '{en,nl}'),
  ('Birk', 'boy', 'Norse', 'Birch tree', null, '{nl}'),
  ('Kasper', 'boy', 'Persian', 'Treasurer', null, '{en,nl}'),
  ('Cillian', 'boy', 'Irish', 'Little church', null, '{en}'),
  ('Astrid', 'girl', 'Norse', 'Divinely beautiful', 10, '{en,nl,fr}'),
  ('Frida', 'girl', 'Germanic', 'Peace', 7, '{en,es,nl,fr,pt}'),
  ('Ellinor', 'girl', 'Old French', 'Shining light', 9, '{en,nl}'),
  ('Fiadh', 'girl', 'Irish', 'Wild, deer', 3, '{en}'),
  ('Saoirse', 'girl', 'Irish', 'Freedom', null, '{en}')
on conflict do nothing;

comment on column public.names.works_in is
  'Languages a native speaker can pronounce this name naturally in: en, es, nl, fr, pt. Empty = untagged (custom names added by the couple).';
