-- Additional real-world spellings from the US Social Security Administration,
-- 2020-2025 top 200: https://www.ssa.gov/oact/babynames/decades/names2020s.html
-- English coverage only; other language tags need review with native speakers.
-- Existing rows keep their IDs, so existing swipes and matches stay intact.
insert into public.names (value, gender, popularity, works_in) values
  ('Elijah', 'boy', 5, '{en}'),
  ('William', 'boy', 6, '{en}'),
  ('Henry', 'boy', 7, '{en}'),
  ('Theodore', 'boy', 9, '{en}'),
  ('Michael', 'boy', 16, '{en}'),
  ('Alexander', 'boy', 17, '{en}'),
  ('Ethan', 'boy', 18, '{en}'),
  ('Owen', 'boy', 20, '{en}'),
  ('John', 'boy', 21, '{en}'),
  ('Asher', 'boy', 22, '{en}'),
  ('Joseph', 'boy', 28, '{en}'),
  ('Jacob', 'boy', 30, '{en}'),
  ('Logan', 'boy', 32, '{en}'),
  ('Luke', 'boy', 33, '{en}'),
  ('Matthew', 'boy', 35, '{en}'),
  ('Dylan', 'boy', 40, '{en}'),
  ('Anthony', 'boy', 46, '{en}'),
  ('Miles', 'boy', 49, '{en}'),
  ('Charles', 'boy', 50, '{en}'),
  ('Caleb', 'boy', 52, '{en}'),
  ('Christopher', 'boy', 57, '{en}'),
  ('Joshua', 'boy', 58, '{en}'),
  ('Andrew', 'boy', 60, '{en}'),
  ('Roman', 'boy', 62, '{en}'),
  ('Cameron', 'boy', 63, '{en}'),
  ('Wesley', 'boy', 67, '{en}'),
  ('Axel', 'boy', 73, '{en}'),
  ('Christian', 'boy', 74, '{en}'),
  ('Eli', 'boy', 75, '{en}'),
  ('Ryan', 'boy', 77, '{en}'),
  ('Jonathan', 'boy', 79, '{en}'),
  ('Beau', 'boy', 80, '{en}'),
  ('Silas', 'boy', 83, '{en}'),
  ('Leonardo', 'boy', 84, '{en}'),
  ('Robert', 'boy', 85, '{en}'),
  ('Thiago', 'boy', 87, '{en}'),
  ('Gael', 'boy', 96, '{en}'),
  ('Dominic', 'boy', 98, '{en}'),
  ('Xavier', 'boy', 100, '{en}'),
  ('Vincent', 'boy', 119, '{en}'),
  ('Jasper', 'boy', 132, '{en}'),
  ('Emiliano', 'boy', 135, '{en}'),
  ('Luis', 'boy', 136, '{en}'),
  ('Carlos', 'boy', 145, '{en}'),
  ('Juan', 'boy', 148, '{en}'),
  ('Jude', 'boy', 154, '{en}'),
  ('Matteo', 'boy', 155, '{en}'),
  ('Leon', 'boy', 157, '{en}'),
  ('Arlo', 'boy', 169, '{en}'),
  ('Antonio', 'boy', 177, '{en}'),
  ('Miguel', 'boy', 196, '{en}'),
  ('Alejandro', 'boy', 198, '{en}'),
  ('Sophia', 'girl', 5, '{en}'),
  ('Ava', 'girl', 8, '{en}'),
  ('Evelyn', 'girl', 9, '{en}'),
  ('Eleanor', 'girl', 14, '{en}'),
  ('Elizabeth', 'girl', 15, '{en}'),
  ('Gianna', 'girl', 16, '{en}'),
  ('Scarlett', 'girl', 17, '{en}'),
  ('Violet', 'girl', 18, '{en}'),
  ('Chloe', 'girl', 21, '{en}'),
  ('Abigail', 'girl', 22, '{en}'),
  ('Aria', 'girl', 23, '{en}'),
  ('Penelope', 'girl', 24, '{en}'),
  ('Ellie', 'girl', 30, '{en}'),
  ('Layla', 'girl', 32, '{en}'),
  ('Eliana', 'girl', 33, '{en}'),
  ('Grace', 'girl', 36, '{en}'),
  ('Lucy', 'girl', 39, '{en}'),
  ('Willow', 'girl', 41, '{en}'),
  ('Victoria', 'girl', 44, '{en}'),
  ('Stella', 'girl', 45, '{en}'),
  ('Leah', 'girl', 50, '{en}'),
  ('Lillian', 'girl', 51, '{en}'),
  ('Delilah', 'girl', 55, '{en}'),
  ('Natalie', 'girl', 58, '{en}'),
  ('Sadie', 'girl', 61, '{en}'),
  ('Ruby', 'girl', 63, '{en}'),
  ('Josephine', 'girl', 64, '{en}'),
  ('Claire', 'girl', 66, '{en}'),
  ('Alice', 'girl', 67, '{en}'),
  ('Audrey', 'girl', 69, '{en}'),
  ('Adeline', 'girl', 70, '{en}'),
  ('Aaliyah', 'girl', 73, '{en}'),
  ('Eloise', 'girl', 77, '{en}'),
  ('Caroline', 'girl', 78, '{en}'),
  ('Vivian', 'girl', 84, '{en}'),
  ('Bella', 'girl', 87, '{en}'),
  ('Gabriella', 'girl', 88, '{en}'),
  ('Cora', 'girl', 92, '{en}'),
  ('Maria', 'girl', 93, '{en}'),
  ('Liliana', 'girl', 95, '{en}'),
  ('Lydia', 'girl', 96, '{en}'),
  ('Athena', 'girl', 98, '{en}'),
  ('Ayla', 'girl', 102, '{en}'),
  ('Daisy', 'girl', 110, '{en}'),
  ('Rose', 'girl', 119, '{en}'),
  ('Sienna', 'girl', 137, '{en}'),
  ('Esther', 'girl', 139, '{en}'),
  ('Catalina', 'girl', 142, '{en}'),
  ('Juliette', 'girl', 148, '{en}'),
  ('Amaya', 'girl', 162, '{en}'),
  ('June', 'girl', 165, '{en}'),
  ('Amira', 'girl', 169, '{en}'),
  ('Rosalie', 'girl', 182, '{en}'),
  ('Gemma', 'girl', 191, '{en}'),
  ('Alexandra', 'girl', 192, '{en}'),
  ('Phoebe', 'girl', 197, '{en}')
on conflict do nothing;

-- Dutch names documented by SVB's 2025 birth-name report:
-- https://www.svb.nl/nl/pers-en-nieuws/nieuwsberichten/noor-en-noah-de-populairste-kindernamen-van-2025
insert into public.names (value, gender, works_in) values
  ('Milou', 'girl', '{nl}'),
  ('Lieke', 'girl', '{nl}'),
  ('Musa', 'boy', '{nl}'),
  ('Oos', 'boy', '{nl}')
on conflict do nothing;

-- Spanish spellings in INE's 2024 birth-name infographic:
-- https://www.ine.es/en/infografias/infografia_nombres_nacidos_en.pdf
insert into public.names (value, gender, works_in) values
  ('Lucía', 'girl', '{es}'),
  ('Martín', 'boy', '{es}'),
  ('Martina', 'girl', '{es}'),
  ('Manuel', 'boy', '{es}'),
  ('Marc', 'boy', '{es}'),
  ('Laia', 'girl', '{es}')
on conflict do nothing;
