-- ---------------------------------------------------------------------------
-- Global name catalogue. Idempotent: safe to re-run on every deploy.
-- Mix of Dutch top-100, international classics, and Spanish/Caribbean names.
-- popularity = rough rank within the gender, lower is more common.
-- ---------------------------------------------------------------------------

insert into public.names (value, gender, origin, meaning, popularity) values
-- boys ---------------------------------------------------------------------
('Noah','boy','Hebrew','Rest, comfort',1),
('Sem','boy','Hebrew','Name, renown',2),
('Liam','boy','Irish','Strong-willed protector',3),
('Lucas','boy','Latin','Light',4),
('Daan','boy','Dutch','God is my judge',5),
('Finn','boy','Irish','Fair, white',6),
('Levi','boy','Hebrew','Joined, attached',7),
('Mees','boy','Dutch','Son of the furrow',8),
('Luuk','boy','Dutch','Light',9),
('James','boy','Hebrew','He who supplants',10),
('Milan','boy','Slavic','Gracious, dear',11),
('Bram','boy','Hebrew','Father of many',12),
('Julian','boy','Latin','Youthful',13),
('Mason','boy','English','Stone worker',14),
('Adam','boy','Hebrew','Earth, man',15),
('Jesse','boy','Hebrew','Gift',16),
('Benjamin','boy','Hebrew','Son of the right hand',17),
('Thomas','boy','Aramaic','Twin',18),
('Sam','boy','Hebrew','God has heard',19),
('Max','boy','Latin','The greatest',20),
('Boaz','boy','Hebrew','Swiftness, strength',21),
('Teun','boy','Dutch','Priceless one',22),
('Jack','boy','English','God is gracious',23),
('Olivier','boy','Latin','Olive tree',24),
('Noud','boy','Dutch','Strong as an eagle',25),
('Hugo','boy','Germanic','Mind, spirit',26),
('Gijs','boy','Dutch','Bright pledge',27),
('Stijn','boy','Dutch','Steadfast',28),
('Ruben','boy','Hebrew','Behold, a son',29),
('Floris','boy','Latin','Flourishing',30),
('Willem','boy','Germanic','Resolute protector',31),
('Tijn','boy','Dutch','Of Mars, warlike',32),
('Sven','boy','Scandinavian','Young man',33),
('Ties','boy','Dutch','Gift of God',34),
('Cas','boy','Dutch','Treasurer',35),
('Jens','boy','Scandinavian','God is gracious',36),
('Lars','boy','Scandinavian','Crowned with laurel',37),
('Nathan','boy','Hebrew','He gave',38),
('Elias','boy','Hebrew','The Lord is my God',39),
('Oliver','boy','Latin','Olive tree',40),
('Vince','boy','Latin','Conquering',41),
('Job','boy','Hebrew','Patient, enduring',42),
('Siem','boy','Dutch','God has heard',43),
('Pepijn','boy','Frankish','Awe-inspiring',44),
('Guus','boy','Dutch','Exalted one',45),
('Mats','boy','Scandinavian','Gift of God',46),
('Joep','boy','Dutch','God will add',47),
('Dean','boy','English','Valley',48),
('Kai','boy','Frisian','Sea, keeper of the keys',49),
('Tobias','boy','Hebrew','God is good',50),
('David','boy','Hebrew','Beloved',51),
('Aaron','boy','Hebrew','Mountain of strength',52),
('Ezra','boy','Hebrew','Help',53),
('Casper','boy','Persian','Treasurer',54),
('Mick','boy','English','Who is like God',55),
('Jurre','boy','Frisian','Farmer',56),
('Melle','boy','Frisian','Gentle chief',57),
('Bas','boy','Dutch','Venerable',58),
('Jort','boy','Dutch','Farmer, earth worker',59),
('Roan','boy','Irish','Little red one',60),
('Arthur','boy','Celtic','Bear, strong',61),
('Otis','boy','Germanic','Wealthy',62),
('Mateo','boy','Spanish','Gift of God',63),
('Rafael','boy','Hebrew','God has healed',64),
('Diego','boy','Spanish','He who supplants',65),
('Enzo','boy','Italian','Ruler of the home',66),
('Leo','boy','Latin','Lion',67),
('Felix','boy','Latin','Lucky, happy',68),
('Victor','boy','Latin','Conqueror',69),
('Julius','boy','Latin','Youthful',70),
('Samuel','boy','Hebrew','God has heard',71),
('Simon','boy','Hebrew','He has heard',72),
('Daniel','boy','Hebrew','God is my judge',73),
('Andres','boy','Spanish','Manly, brave',74),
('Marco','boy','Latin','Of Mars, warlike',75),
('Emilio','boy','Spanish','Eager, striving',76),
('Santiago','boy','Spanish','Saint James',77),
('Luca','boy','Italian','Light',78),
('Milo','boy','Germanic','Merciful, gentle',79),
('Nino','boy','Italian','God is gracious',80),
('Lev','boy','Hebrew','Heart',81),
('Xavi','boy','Basque','New house',82),
('Ivan','boy','Slavic','God is gracious',83),
('Lenn','boy','Germanic','Brave as a lion',84),
('Hidde','boy','Frisian','Battle, fight',85),
('Jaxx','boy','English','Son of Jack',86),
('Riley','boy','Irish','Courageous',87),
('Seth','boy','Hebrew','Appointed',88),
('Joah','boy','Hebrew','The Lord is brother',89),
('Amir','boy','Arabic','Prince, commander',90),
-- girls --------------------------------------------------------------------
('Emma','girl','Germanic','Whole, universal',1),
('Julia','girl','Latin','Youthful',2),
('Mila','girl','Slavic','Gracious, dear',3),
('Sophie','girl','Greek','Wisdom',4),
('Tess','girl','English','Harvester',5),
('Nora','girl','Latin','Honour, light',6),
('Yara','girl','Arabic','Small butterfly',7),
('Saar','girl','Hebrew','Princess',8),
('Olivia','girl','Latin','Olive tree',9),
('Lotte','girl','Germanic','Free woman',10),
('Evi','girl','Hebrew','Life',11),
('Liv','girl','Norse','Life, shelter',12),
('Anna','girl','Hebrew','Grace',13),
('Nova','girl','Latin','New',14),
('Sara','girl','Hebrew','Princess',15),
('Fenna','girl','Frisian','Peace',16),
('Eva','girl','Hebrew','Life',17),
('Elin','girl','Scandinavian','Bright, shining',18),
('Maeve','girl','Irish','She who rules',19),
('Isa','girl','Hebrew','God is my oath',20),
('Noor','girl','Arabic','Light',21),
('Roos','girl','Dutch','Rose',22),
('Fleur','girl','French','Flower',23),
('Sofia','girl','Greek','Wisdom',24),
('Hannah','girl','Hebrew','Grace',25),
('Nina','girl','Spanish','Little girl',26),
('Jasmijn','girl','Persian','Jasmine flower',27),
('Lynn','girl','Welsh','Lake',28),
('Suze','girl','Hebrew','Lily',29),
('Juul','girl','Latin','Youthful',30),
('Maud','girl','Germanic','Mighty in battle',31),
('Sien','girl','Dutch','The Lord is gracious',32),
('Elena','girl','Greek','Shining light',33),
('Lily','girl','English','Lily flower',34),
('Emily','girl','Latin','Eager, striving',35),
('Vera','girl','Latin','Truth, faith',36),
('Merel','girl','Dutch','Blackbird',37),
('Isabel','girl','Hebrew','God is my oath',38),
('Nine','girl','Dutch','Grace',39),
('Puck','girl','Dutch','Mischievous sprite',40),
('Feline','girl','Latin','Cat-like, playful',41),
('Lieve','girl','Dutch','Dear, beloved',42),
('Charlotte','girl','Germanic','Free woman',43),
('Amber','girl','Arabic','Jewel, amber',44),
('Lena','girl','Greek','Light',45),
('Isabella','girl','Hebrew','God is my oath',46),
('Luna','girl','Latin','Moon',47),
('Mara','girl','Hebrew','Strong, bitter-sweet',48),
('Livia','girl','Latin','Life, envy',49),
('Nienke','girl','Frisian','Grace',50),
('Femke','girl','Frisian','Peace, little girl',51),
('Noa','girl','Hebrew','Movement',52),
('Jade','girl','Spanish','Green gemstone',53),
('Aya','girl','Arabic','Miracle, sign',54),
('Ella','girl','Germanic','All, complete',55),
('Lara','girl','Latin','Shining, famous',56),
('Kiki','girl','Dutch','Follower of Christ',57),
('Fay','girl','French','Fairy',58),
('Valentina','girl','Latin','Strong, healthy',59),
('Camila','girl','Latin','Young attendant',60),
('Isla','girl','Scottish','Island',61),
('Mia','girl','Italian','Mine, beloved',62),
('Carmen','girl','Spanish','Song',63),
('Paloma','girl','Spanish','Dove',64),
('Aurora','girl','Latin','Dawn',65),
('Freya','girl','Norse','Lady, goddess of love',66),
('Iris','girl','Greek','Rainbow',67),
('Philine','girl','Greek','Loving',68),
('Roosmarijn','girl','Dutch','Rosemary, dew of the sea',69),
('Cato','girl','Latin','Wise one',70),
('Hazel','girl','English','Hazel tree',71),
('Ivy','girl','English','Faithful, ivy',72),
('Juna','girl','Latin','Young',73),
('Sofie','girl','Greek','Wisdom',74),
('Naomi','girl','Hebrew','Pleasantness',75),
('Rosa','girl','Latin','Rose',76),
('Ada','girl','Germanic','Noble',77),
('Elisa','girl','Hebrew','God is my oath',78),
('Nola','girl','Irish','White shoulder',79),
('Loulou','girl','French','Famous warrior',80),
('Indy','girl','English','Independent',81),
('Alicia','girl','Germanic','Noble',82),
('Hailey','girl','English','Hay meadow',83),
('Pippa','girl','Greek','Lover of horses',84),
('Guusje','girl','Dutch','Exalted one',85),
('Fem','girl','Frisian','Peace',86),
('Lois','girl','Greek','Most desirable',87),
('Zoe','girl','Greek','Life',88),
('Lauren','girl','Latin','Crowned with laurel',89),
('Amy','girl','Latin','Beloved',90),
-- unisex -------------------------------------------------------------------
('Robin','unisex','Germanic','Bright fame',1),
('Charlie','unisex','English','Free',2),
('Quinn','unisex','Irish','Wise, counsel',3),
('Jamie','unisex','Scottish','He who supplants',4),
('Alex','unisex','Greek','Defender of people',5),
('River','unisex','English','Flowing water',6),
('Eden','unisex','Hebrew','Delight, paradise',7),
('Rowan','unisex','Irish','Little red one',8),
('Sasha','unisex','Slavic','Defender',9),
('Lou','unisex','Germanic','Famous warrior',10),
('Micah','unisex','Hebrew','Who is like God',11),
('Remy','unisex','French','Oarsman',12),
('Toni','unisex','Latin','Priceless one',13),
('Sage','unisex','Latin','Wise, herb',14),
('Kim','unisex','English','Royal, bold',15),
('Wren','unisex','English','Small bird',16),
('Nico','unisex','Greek','Victory of the people',17),
('Amari','unisex','African','Strength',18),
('Shay','unisex','Irish','Admirable',19),
('Ariel','unisex','Hebrew','Lion of God',20),
('Jules','unisex','Latin','Youthful',21),
('Sol','unisex','Spanish','Sun',22),
('Sky','unisex','English','Sky, boundless',23),
('Bo','unisex','Norse','To live',24),
('Ray','unisex','English','Counsel, protection',25)
on conflict do nothing;
